using SnoopCompileCore
using Pkg

pkgInvalidations = []
# for (package, version) in Pkg.installed() # Pkg.dependencies()
for (uuid, pkginfo) in Pkg.dependencies()
	package, version, direct_depenency, custom_path = pkginfo.name, pkginfo.version, pkginfo.is_direct_dep, pkginfo.is_tracking_path
	custom_path && (println("$package with custompath is left out for safety reason!"); continue)
	!direct_depenency && continue
	println(package)
	invs = @snoopr @eval using $(Symbol(package))
	push!(pkgInvalidations, (package, invs))
end

using SnoopCompile
using SnoopCompile: countchildren
using Printf
toprints=[]
for (package,invs) in pkgInvalidations
	try
		trees = invalidation_trees(invs)
		push!(toprints, (pkgname=package, invfunc=length(trees), sumchildren=sum([countchildren(tree) for tree in trees]), invalidations=length(invs)) )
	catch
		println("$package had an error at invalidation check!")
	end
end
sort!(toprints, by=x -> x[:sumchildren], rev=true)
for toprint in toprints
	@printf "%-20s: invalidations: %3d which invalidated: %5d children (%5d invalidations)\n" toprint[:pkgname] toprint[:invfunc] toprint[:sumchildren] toprint[:invalidations]
end

#%%  2022.06.21
# CUDA                : invalidations:  21 which invalidated:  1058 children ( 2492 invalidations)
# SnoopCompile        : invalidations:  15 which invalidated:   677 children ( 1558 invalidations)
# UnicodePlots        : invalidations:   8 which invalidated:   115 children (  363 invalidations)
# Cthulhu             : invalidations:  14 which invalidated:    95 children (  752 invalidations)
# PlotlyBase          : invalidations:   1 which invalidated:    25 children (   70 invalidations)
# VideoIO             : invalidations:   1 which invalidated:    23 children (   68 invalidations)
# LRUCache            : invalidations:   1 which invalidated:    22 children (   96 invalidations)
# JuliaFormatter      : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# GraphPlot           : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# GraphMakie          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# SparseArrays        : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# GLMakie             : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# ProgressMeter       : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# JSON2               : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# FiniteDifferences   : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Formatting          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# TensorBoardLogger   : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# FileIO              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Random              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# HTTP                : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# CodeTracking        : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Memoize             : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# EllipsisNotation    : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# JLD2                : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Revise              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# JSON                : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# BenchmarkTools      : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# SnoopCompileCore    : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Zygote              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# PackageCompiler     : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Graphs              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# ChainRules          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Colors              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# DataStructures      : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Distributed         : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# ClusterManagers     : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Glob                : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# WebSockets          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# DiffRules           : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Plots               : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# JuliaInterpreter    : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# PyCall              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# LoopVectorization   : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# OrderedCollections  : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# AbstractTrees       : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# ThreadTools         : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# FastClosures        : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# KernelDensity       : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# KernelAbstractions  : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# MacroTools          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Printf              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Crayons             : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# GeometryBasics      : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# CairoMakie          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Makie               : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Requires            : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Distributions       : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# FastBroadcast       : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Parameters          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# MethodAnalysis      : invalidations:   0 which invalidated:     0 children (    0 invalidations)
#%% 
# Optimised image: 
# AbstractPlotting    : invalidations:  11 which invalidated:   190 children ( 1399 invalidations)
# LRUCache            : invalidations:   1 which invalidated:     7 children (   94 invalidations)
# MethodAnalysis      : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# PrecompilePkg       : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Memoize             : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# EllipsisNotation    : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# HTTP                : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# OrderedCollections  : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# PlotlyBase          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# JuliaInterpreter    : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# FastClosures        : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# DataStructures      : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# GeometryTypes       : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Glob                : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# JLD2                : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Zygote              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Boilerplate         : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# JSON3               : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Distributions       : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# JSON2               : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Formatting          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# GraphPlot           : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# FileIO              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# SnoopCompile        : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# PackageCompiler     : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# CSV                 : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Revise              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# BenchmarkTools      : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# SnoopCompileCore    : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# ClusterManagers     : invalidations:   1 which invalidated:     0 children (    5 invalidations)
# PyCall              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Flux                : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Plots               : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Parameters          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# CUDA                : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# LightGraphs         : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# NetworkLayout       : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# JuliaFormatter      : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# DiffRules           : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Colors              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# WebSockets          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Crayons             : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# MacroTools          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# AbstractTrees       : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# ChainRulesCore      : invalidations:   0 which invalidated:     0 children (    0 invalidations)

# OLD image: 
# StatsPlots          : invalidations:  25 which invalidated:  2919 children ( 6785 invalidations)
# PyCall              : invalidations:  11 which invalidated:  2537 children ( 5881 invalidations)
# JSON3               : invalidations:   4 which invalidated:  1191 children ( 2406 invalidations)
# EllipsisNotation    : invalidations:   6 which invalidated:   932 children ( 2195 invalidations)
# HTTP                : invalidations:   4 which invalidated:   470 children (  978 invalidations)
# JLD2                : invalidations:   3 which invalidated:   266 children (  591 invalidations)
# Flux                : invalidations:  20 which invalidated:   189 children ( 1484 invalidations)
# PlotlyBase          : invalidations:   4 which invalidated:   149 children (  314 invalidations)
# JuliaFormatter      : invalidations:   2 which invalidated:   111 children (  264 invalidations)
# GeometryTypes       : invalidations:  11 which invalidated:    77 children (  419 invalidations)
# BenchmarkTools      : invalidations:   2 which invalidated:    73 children (  156 invalidations)
# DataStructures      : invalidations:   5 which invalidated:    11 children (   50 invalidations)
# Zygote              : invalidations:   7 which invalidated:    11 children (  118 invalidations)
# MethodAnalysis      : invalidations:   2 which invalidated:    10 children (  142 invalidations)
# KernelDensity       : invalidations:   1 which invalidated:     8 children (   40 invalidations)
# GraphPlot           : invalidations:   1 which invalidated:     8 children (   37 invalidations)
# AbstractPlotting    : invalidations:   2 which invalidated:     7 children (  428 invalidations)
# LoopVectorization   : invalidations:   1 which invalidated:     3 children (   88 invalidations)
# SnoopCompile        : invalidations:   2 which invalidated:     1 children (   94 invalidations)
# Memoize             : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# OrderedCollections  : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# JuliaInterpreter    : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# FastClosures        : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Glob                : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Boilerplate         : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Distributions       : invalidations:   0 which invalidated:     0 children (   70 invalidations)
# JSON2               : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Formatting          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# FileIO              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# PackageCompiler     : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# CSV                 : invalidations:   0 which invalidated:     0 children (   34 invalidations)
# Revise              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# SnoopCompileCore    : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# ClusterManagers     : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Plots               : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# LRUCache            : invalidations:   0 which invalidated:     0 children (   62 invalidations)
# Parameters          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Redis               : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# CUDA                : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# LightGraphs         : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# NetworkLayout       : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# DiffRules           : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Colors              : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# WebSockets          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# Crayons             : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# MacroTools          : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# ChainRulesCore      : invalidations:   0 which invalidated:     0 children (    0 invalidations)
# ORCA                : invalidations:   0 which invalidated:     0 children (    0 invalidations)

